### PR TITLE
fix: include widths.json as a julia file

### LINKED ISSUE #7: InitError in CI - pathof(Badges) returns nothing
`dirname(pathof(Badges))` in `__init__` broken in CI

```
#30 41.42 ERROR: LoadError: InitError: MethodError: no method matching dirname(::Nothing)
#30 41.42 The function `dirname` exists, but no method is defined for this combination of argument types.
#30 41.42 
#30 41.42 Closest candidates are:
#30 41.42   dirname(!Matched::AbstractString)
#30 41.42    @ Base path.jl:183
#30 41.42 
#30 41.42 Stacktrace:
#30 41.42   [1] __init__()
#30 41.42     @ Badges /depot/packages/Badges/D3JuT/src/Badges.jl:299
#30 41.42   [2] run_module_init(mod::Module, i::Int64)
#30 41.42     @ Base ./loading.jl:1336
#30 41.42   [3] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
#30 41.42     @ Base ./loading.jl:1324
#30 41.42   [4] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any}, ignore_native::Nothing; register::Bool)
#30 41.42     @ Base ./loading.jl:1213
#30 41.42   [5] _include_from_serialized (repeats 2 times)
#30 41.42     @ ./loading.jl:1169 [inlined]
#30 41.42   [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128, stalecheck::Bool; reasons::Dict{String, Int64}, DEPOT_PATH::Vector{String})
#30 41.42     @ Base ./loading.jl:1975
#30 41.42   [7] _require(pkg::Base.PkgId, env::String)
#30 41.42     @ Base ./loading.jl:2435
#30 41.42   [8] __require_prelocked(uuidkey::Base.PkgId, env::String)
#30 41.42     @ Base ./loading.jl:2300
#30 41.42   [9] #invoke_in_world#3
#30 41.42     @ ./essentials.jl:1088 [inlined]
#30 41.42  [10] invoke_in_world
#30 41.42     @ ./essentials.jl:1085 [inlined]
#30 41.42  [11] _require_prelocked(uuidkey::Base.PkgId, env::String)
#30 41.42     @ Base ./loading.jl:2287
#30 41.42  [12] macro expansion
#30 41.42     @ ./loading.jl:2226 [inlined]
#30 41.42  [13] macro expansion
#30 41.42     @ ./lock.jl:273 [inlined]
#30 41.42  [14] __require(into::Module, mod::Symbol)
#30 41.42     @ Base ./loading.jl:2183
#30 41.42  [15] #invoke_in_world#3
#30 41.42     @ ./essentials.jl:1088 [inlined]
#30 41.42  [16] invoke_in_world
#30 41.42     @ ./essentials.jl:1085 [inlined]
#30 41.42  [17] require(into::Module, mod::Symbol)
#30 41.42     @ Base ./loading.jl:2176
#30 41.42  [18] include(mod::Module, _path::String)
#30 41.42     @ Base ./Base.jl:557
#30 41.42 during initialization of module Badges
```

### PR DESCRIPTION
**Pull request by krynju**
fixes https://github.com/JuliaComputing/Badges.jl/issues/7

### CODE REVIEW

File: src/widths.jl [hunk 1]
```diff
@@ -1 +1,4 @@
...
\ No newline at end of file
+const WIDTHS = JSON3.read(
```
Comment (aviks) [inline src/widths.jl]: Do we still need JSON3 here? Can't we place it as a literal array?

File: src/Badges.jl [hunk 2]
```diff
@@ -277,13 +274,13 @@ If `approx` is true, any unknwon character will be measured as 'm'. Otherwise 0.
 """
 function widthOfCharCode(charCode; approx=true)
     if isControlChar(charCode); return 0.0; end
-    res = findfirst(data[]) do x
+    res = findfirst(DATA) do x
```
Comment (aviks) [inline src/Badges.jl]:
```suggestion
    res = findfirst(WIDTHS) do x
```

File: src/Badges.jl [hunk 3]
```diff
@@ -277,13 +274,13 @@ If `approx` is true, any unknwon character will be measured as 'm'. Otherwise 0.
...
         charCode >= x[1] && charCode <= x[2]
     end
     if isnothing(res)
-        if approx; return em[]; else return 0.0; end
+        if approx; return EM; else return 0.0; end
     else
-        return data[][res][3]
+        return DATA[res][3]
```
Comment (aviks) [inline src/Badges.jl]:
```suggestion
        return WIDTHS[res][3]
```

File: src/Badges.jl [hunk 4]
```diff
@@ -294,11 +291,10 @@ widthOf(text::AbstractString; approx=true) = reduce(+, [widthOfCharCode(Int(x),
...
 
+# Verdana font metrics precalculated from the npm package anafanafo
+# =================================================================
 
-function __init__()
-    modulepath = dirname(pathof(Badges))
-    data[] = JSON3.read(read("$modulepath/widths.json", String))
-    em[] = widthOfCharCode(Int('m'))
-end
+const DATA = WIDTHS # from widths.jl
```
Comment (aviks) [inline src/Badges.jl]:
```suggestion
```

File: src/widths.jl (hunk 1 above)
Comment (krynju) [reply src/widths.jl]: It parses as the inner array as Float64 (instead of Int, Int, Float64)
But it's ok I think. Shouldn't be an issue with the current code `charCode >= x[1] && charCode <= x[2]`

```
julia> [32,32,38.67]
3-element Vector{Float64}:
 32.0
 32.0
 38.67
```

Comment (krynju) [reply src/widths.jl]: Ok regexed it into a tuple with correct types

```
julia> Badges.WIDTHS
10035-element Vector{Tuple{Tuple{Int64, Int64}, Float64}}:
 ((32, 32), 38.67)
 ((33, 33), 43.29)
 ((34, 34), 50.49)
 ((35, 35), 90.02)
```
